In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head(5)

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [21]:
from sklearn.model_selection import train_test_split

X = df.drop("purchased", axis=1)
y = df["purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
y_train


,purchased
12,No
4,No
37,Yes
8,No
3,No
6,No
41,Yes
46,No
47,Yes
15,No


In [14]:
X_train.shape, X_test.shape

((40, 2), (10, 2))

In [15]:
X_test

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

In [11]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[
    ["Poor", "Average", "Good"],
    ["School", "UG", "PG"]
])

encoder.fit(X_train)

X_train = encoder.transform(X_train)
X_test = encoder.transform(X_test)

In [13]:
X_test

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

In [19]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(y_train)

y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)

In [20]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [22]:
%cd /content

/content


In [23]:
!git clone https://github.com/ahmad-0313/Machine-Learning-Practice.git

Cloning into 'Machine-Learning-Practice'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 12 (delta 1), reused 5 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 12.71 KiB | 12.71 MiB/s, done.
Resolving deltas: 100% (1/1), done.


In [24]:
!mkdir -p /content/Machine-Learning-Practice/OrdinalLabelEncoding

In [25]:
!cp "/content/drive/MyDrive/Colab Notebooks/Ordinal Label Encoding.ipynb" "/content/Machine-Learning-Practice/OrdinalLabelEncoding/"

cp: cannot stat '/content/drive/MyDrive/Colab Notebooks/Ordinal Label Encoding.ipynb': No such file or directory


In [27]:
!find "/content/drive/MyDrive/Colab Notebooks" -name "*.ipynb"

find: ‘/content/drive/MyDrive/Colab Notebooks’: No such file or directory


In [28]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [29]:
!find "/content/drive/MyDrive/Colab Notebooks" -name "*.ipynb"

/content/drive/MyDrive/Colab Notebooks/Ordinal Label Encoding.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled0.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled1.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled2.ipynb
/content/drive/MyDrive/Colab Notebooks/test run.ipynb
/content/drive/MyDrive/Colab Notebooks/Test.ipynb
/content/drive/MyDrive/Colab Notebooks/Normalization.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of Ordinal Label Encoding.ipynb


In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/Ordinal Label Encoding.ipynb" "/content/Machine-Learning-Practice/OrdinalLabelencoding/"